import { useMemo } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
  CheckCircle2,
  CircleDashed,
  Lock,
  Map as MapIcon,
  PlayCircle,
  RefreshCw,
  Route,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { useCurriculum, useMastery, usePrerequisites, useRecommendations } from "@/hooks/useLearning";
import {
  MasteryBar,
  PageHeader,
  RecommendationCard,
  recommendationHref,
} from "@/components/learning/primitives";
import { EmptyState, ErrorState, LoadingState } from "@/components/states";
import { callFunction, errorMessage } from "@/lib/api";
import { decayRisk } from "@/lib/mastery";
import { toast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

/**
 * Roadmap — the order to learn things in, and where you actually are on it.
 *
 * The order comes from the curriculum's own positions and prerequisite edges;
 * the position on it comes from measured mastery. Nothing is generated by a
 * model here, which is why the page still works with every API key missing.
 *
 * "Locked" means a prerequisite is below 60% — it is stated with the reason and
 * the lesson stays reachable. A roadmap that hides material is a roadmap the
 * student stops trusting.
 */

type Step = "mastered" | "practising" | "review" | "ready" | "locked";

const STEP_META: Record<Step, { label: string; icon: typeof CheckCircle2; className: string }> = {
  mastered: { label: "Mastered", icon: CheckCircle2, className: "text-success border-success/40 bg-success/10" },
  practising: { label: "In progress", icon: PlayCircle, className: "text-primary border-primary/40 bg-primary/10" },
  review: { label: "Needs review", icon: RefreshCw, className: "text-warning border-warning/40 bg-warning/10" },
  ready: { label: "Ready to start", icon: CircleDashed, className: "text-muted-foreground border-border bg-muted" },
  locked: { label: "Comes later", icon: Lock, className: "text-muted-foreground border-border bg-muted" },
};

const Roadmap = () => {
  const queryClient = useQueryClient();
  const curriculum = useCurriculum();
  const mastery = useMastery();
  const prerequisites = usePrerequisites();
  const recommendations = useRecommendations();

  const titleById = useMemo(() => {
    const map = new Map<string, string>();
    for (const course of curriculum.data ?? []) {
      for (const chapter of course.chapters) {
        for (const concept of chapter.concepts) map.set(concept.id, concept.title);
      }
    }
    return map;
  }, [curriculum.data]);

  const blockers = useMemo(() => {
    const map = new Map<string, string[]>();
    for (const edge of prerequisites.data ?? []) {
      const record = mastery.data?.get(edge.prerequisite_id);
      if ((record?.mastery ?? 0) >= 60) continue;
      const name = titleById.get(edge.prerequisite_id);
      if (!name) continue;
      map.set(edge.concept_id, [...(map.get(edge.concept_id) ?? []), name]);
    }
    return map;
  }, [prerequisites.data, mastery.data, titleById]);

  const stepFor = (conceptId: string): Step => {
    const record = mastery.data?.get(conceptId);
    if (record && record.attempts > 0) {
      if (decayRisk(record.peak_mastery, record.mastery, record.last_practiced_at) >= 40) return "review";
      if (record.mastery >= 85) return "mastered";
      return "practising";
    }
    return blockers.has(conceptId) ? "locked" : "ready";
  };

  const plan = useMutation({
    mutationFn: () =>
      callFunction<{ recommendations: unknown[]; hasEvidence: boolean }>("learning-plan"),
    onSuccess: (result) => {
      void queryClient.invalidateQueries({ queryKey: ["recommendations"] });
      void queryClient.invalidateQueries({ queryKey: ["streak"] });
      toast({
        title: result.hasEvidence ? "Roadmap updated" : "Not enough evidence yet",
        description: result.hasEvidence
          ? `${result.recommendations.length} recommendation${result.recommendations.length === 1 ? "" : "s"} from your latest answers.`
          : "Answer a few questions — or take the placement check — and the plan will have something to work from.",
      });
    },
    onError: (error) =>
      toast({ title: "Could not rebuild the roadmap", description: errorMessage(error), variant: "destructive" }),
  });

  if (curriculum.isLoading || mastery.isLoading) return <LoadingState label="Building your roadmap…" />;
  if (curriculum.error) {
    return <ErrorState error={curriculum.error} onRetry={() => void curriculum.refetch()} />;
  }

  const courses = curriculum.data ?? [];
  const allConcepts = courses.flatMap((course) => course.chapters).flatMap((chapter) => chapter.concepts);
  const counts = allConcepts.reduce<Record<Step, number>>(
    (totals, concept) => {
      const step = stepFor(concept.id);
      totals[step] += 1;
      return totals;
    },
    { mastered: 0, practising: 0, review: 0, ready: 0, locked: 0 },
  );

  const items = recommendations.data ?? [];

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Roadmap"
        title="Your learning path"
        description="Ordered by the curriculum's own prerequisites. Your position on it is measured from the questions you have answered, not from pages you have opened."
        actions={
          <Button variant="outline" onClick={() => plan.mutate()} disabled={plan.isPending || allConcepts.length === 0}>
            <RefreshCw className={cn("mr-2 h-4 w-4", plan.isPending && "animate-spin")} aria-hidden />
            {plan.isPending ? "Rebuilding…" : "Rebuild plan"}
          </Button>
        }
      />

      {allConcepts.length === 0 ? (
        <Card className="surface-card">
          <CardContent className="p-0">
            <EmptyState
              icon={<MapIcon className="h-8 w-8" aria-hidden />}
              title="No path to draw yet"
              description="A roadmap needs published concepts. Once faculty publish a course, the order appears here automatically from its chapters and prerequisites."
            />
          </CardContent>
        </Card>
      ) : (
        <>
          <div className="flex flex-wrap gap-2">
            {(Object.keys(STEP_META) as Step[])
              .filter((step) => counts[step] > 0)
              .map((step) => {
                const Icon = STEP_META[step].icon;
                return (
                  <span
                    key={step}
                    className={cn(
                      "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium",
                      STEP_META[step].className,
                    )}
                  >
                    <Icon className="h-3 w-3" aria-hidden />
                    {counts[step]} {STEP_META[step].label.toLowerCase()}
                  </span>
                );
              })}
          </div>

          {items.length > 0 ? (
            <section>
              <div className="mb-3 flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-primary" aria-hidden />
                <h2 className="text-lg font-semibold">Next on your plan</h2>
              </div>
              <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
                {items.slice(0, 3).map((item) => {
                  const slug = allConcepts.find((concept) => concept.id === item.concept_id)?.slug ?? null;
                  return (
                    <RecommendationCard
                      key={item.id}
                      action={item.action}
                      title={item.title}
                      reason={item.reason}
                      estimatedMinutes={item.estimated_minutes}
                      priority={item.priority}
                      href={recommendationHref(item.action, slug)}
                    />
                  );
                })}
              </div>
            </section>
          ) : null}

          {courses.map((course) => (
            <section key={course.id} className="space-y-4">
              <div className="flex flex-wrap items-baseline gap-2">
                <Route className="h-4 w-4 text-primary" aria-hidden />
                <h2 className="text-lg font-semibold">{course.title}</h2>
                <Badge variant="secondary" className="text-[10px]">
                  {course.subject}
                </Badge>
              </div>

              {course.chapters.map((chapter) => (
                <div key={chapter.id} className="space-y-2">
                  <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    {chapter.title}
                  </h3>

                  <ol className="relative space-y-2 border-l border-border/70 pl-5">
                    {chapter.concepts.map((concept) => {
                      const step = stepFor(concept.id);
                      const meta = STEP_META[step];
                      const Icon = meta.icon;
                      const record = mastery.data?.get(concept.id);
                      const why = blockers.get(concept.id);

                      return (
                        <li key={concept.id} className="relative">
                          <span
                            className={cn(
                              "absolute -left-[27px] top-3 grid h-4 w-4 place-items-center rounded-full border",
                              meta.className,
                            )}
                            aria-hidden
                          >
                            <Icon className="h-2.5 w-2.5" />
                          </span>

                          <Link
                            to={`/learn/${concept.slug}`}
                            className="block rounded-xl border border-border/60 bg-card/60 p-3 transition-colors hover:border-primary/40"
                          >
                            <div className="flex flex-wrap items-start justify-between gap-2">
                              <div className="min-w-0">
                                <p className="text-sm font-medium leading-snug">{concept.title}</p>
                                <p className="mt-0.5 text-[11px] text-muted-foreground">
                                  {step === "locked" && why
                                    ? `Easier after ${why.join(" and ")}`
                                    : `${meta.label} · ${concept.estimated_minutes} min`}
                                </p>
                              </div>
                              <div className="w-full max-w-[140px] shrink-0 sm:w-36">
                                <MasteryBar
                                  value={record?.mastery ?? 0}
                                  unmeasured={(record?.attempts ?? 0) === 0}
                                  showLabel={false}
                                />
                              </div>
                            </div>
                          </Link>
                        </li>
                      );
                    })}
                  </ol>
                </div>
              ))}
            </section>
          ))}
        </>
      )}
    </div>
  );
};

export default Roadmap;
